backend        = "glx";
vsync          = true;
dithered-present = false;
use-damage     = true;

shadow               = true;
shadow-radius        = 14;
shadow-offset-x      = -7;
shadow-offset-y      = -7;
shadow-opacity       = 0.5;
shadow-color         = "#000000";

fading          = true;
fade-in-step    = 0.04;
fade-out-step   = 0.04;
fade-delta      = 4;
no-fading-openclose = false;

corner-radius   = 10;

detect-rounded-corners   = true;
detect-client-opacity    = true;
detect-transient         = true;

blur: {
  method    = "dual_kawase";
  strength  = 7;
}

rules: (
  { blur-background = false; fade = false; },

  { match = "window_type = 'normal'"; fade = true; shadow = true; },
  { match = "window_type = 'dialog'"; shadow = true; },
  { match = "window_type = 'tooltip'"; corner-radius = 0; opacity = 0.90; },
  { match = "fullscreen"; corner-radius = 0; },
  { match = "window_type = 'dock'"; corner-radius = 0; fade = true; blur-background = false; shadow = false; },

  {
    match = "class_g = 'kitty'";
    opacity = 0.92;
    blur-background = true;
  },
  {
    match = "class_g = 'Rofi'";
    opacity = 1.0;
    blur-background = true;
    corner-radius = 12;
  },
  {
    match = "class_g = 'firefox'";
    blur-background = false;
  },
  {
    match = "class_g = 'Polybar' || class_g = 'Dunst'";
    corner-radius = 0;
    shadow = false;
    blur-background = false;
  },
  {
    match = "name = 'Notification' || class_g = 'Dunst' || class_g = 'Polybar' || class_g = 'Rofi' || _GTK_FRAME_EXTENTS@";
    shadow = false;
  }
)
